Unpackerr/unpackerr

cmd/unpacker-poller/helpers.go

Running into a bug where some archives have dozens or hundreds of `.rar` files that are all part of a multi-part archive. This contribution aims to grab only `part1` and ignore the rest.
Also added some more logging.

Grab only first file in multi-part archives.

---

unpackerpoller/helpers.go
unpackerpoller/pollers.go
unpackerpoller/start.go
unpackerpoller/types.go

Updates to newer Deluge library. See https://github.com/golift/deluge/pull/2 (requires this)

Update Deluge library usage.

---

.travis.yml
Gopkg.lock
Gopkg.toml
examples/MANUAL.md
examples/up.conf.example
init/systemd/unpacker-poller.service
unpackerpoller/extracts.go
unpackerpoller/helpers.go
unpackerpoller/pollers.go
unpackerpoller/start.go
unpackerpoller/types.go

Reorganized a bunch of structs. Moved to new flag package. Moved debug into config file (from flags).
Made a New() function to create a usable struct. Cleaned up several methods in start.go. Updated vendors including Starr and Deluge libs.

Major cleanup.

---

README.md
examples/up.conf.example
unpackerpoller/extracts.go
unpackerpoller/pollers.go
unpackerpoller/start.go
unpackerpoller/types.go

This contribution provides a lot of cleanup. I also added a finished counter so you know how many things have been extracted and deleted since the app's start.
This also fixes #7.

Cleanup and finished counter output

---

README.md
examples/unpackerr.conf.example
go.mod
go.sum
unpacker/pollers.go
unpacker/start.go

make lidarr path automatic and unneeded in config.

make lidarr path automatic

---

pkg/unpackerr/webhook.go
pkg/unpackerr/webhook_samples.go

Make changes to how the payload is processed so we can expose the error.

Control the whole webhook payload.

---

.travis.yml
go.mod
go.sum
pkg/unpackerr/handlers.go
pkg/unpackerr/lidarr.go
pkg/unpackerr/radarr.go
pkg/unpackerr/readarr.go
pkg/unpackerr/sonarr.go
settings.sh

This serves only to update the Starr library to v0.9.9.

Update starr library. 

---

README.md
examples/unpackerr.conf.example
go.mod
go.sum
init/docker/Dockerfile
pkg/unpackerr/apps.go
pkg/unpackerr/handlers.go
pkg/unpackerr/lidarr.go
pkg/unpackerr/logs.go
pkg/unpackerr/radarr.go
pkg/unpackerr/readarr.go
pkg/unpackerr/sonarr.go
pkg/unpackerr/start.go

Adds more logs, fixes delete_orig, fixes TZ bug.

---

README.md
examples/unpackerr.conf.example
pkg/unpackerr/apps.go
pkg/unpackerr/folder.go
pkg/unpackerr/start.go
pkg/unpackerr/webhook.go
pkg/unpackerr/webhook_samples.go
pkg/unpackerr/webhooks_templates.go

This fixes a handful of bugs I found in Webhooks while testing with another user. We also added Telegram Webhooks. Closes #73.

Fixes + Telegram webhooks

---

README.md

can you edit the git page description too :)

(git) alpha-order *arrs

---

init/docker/hooks/README.md
settings.sh

Allow building docker locally since dockerhub took away builds

Allow building docker locally since dockerhub took away builds

---

examples/docker-compose.yml

Now matches the keys here:
https://github.com/davidnewhall/unpackerr#command-hooks

Fix example yml file for command hooks

---

.golangci.yml
README.md
examples/unpackerr.conf.example
go.mod
go.sum
main.go
pkg/unpackerr/folder.go
pkg/unpackerr/handlers.go
pkg/unpackerr/logs.go

Extract isos

---

README.md
examples/unpackerr.conf.example
pkg/unpackerr/handlers.go
pkg/unpackerr/lidarr.go
pkg/unpackerr/radarr.go
pkg/unpackerr/readarr.go
pkg/unpackerr/sonarr.go

Skip Starr folders with syncthing .tmp files

---

pkg/unpackerr/start.go
pkg/unpackerr/tray.go

Going to add a few things in here.
- Add uid and gid to startup.
- Fixes the panic in #246, but I'm not sure what it will do now. Probably hang waiting for a tray that it can't access. Need more info to make this a better experience.

Mixups fixups

---

pkg/unpackerr/webhooks_templates.go

unfinished - needs testing and a blurb somewhere about the telegram url that's required.

fix telegram template

---

pkg/unpackerr/logs.go

- Fixes #304 
- Sends error messages to stderr.

Output errors to stderr.

---

.github/workflows/release.yml
settings.sh

- This pushes a docker container into GHCR. 
- Closes #349

Add build for ghcr.

---

.github/workflows/release.yml
Makefile
go.mod
go.sum

- I think this will create semver tags, but need to cut a release to test it. 
- Closes #383.
- Update `cnfg` to fix https://github.com/Unpackerr/unpackerr.github.io/pull/13

Add semver tags to ghcr docker images.

---

.github/workflows/release.yml

add one more tag value for each release.

add v to docker tags

---

.github/workflows/release.yml
pkg/unpackerr/folder.go

Fix the bug with the folder poller.
- Closes #382

Make folder watcher work better

---

pkg/ui/dlgs.go
pkg/unpackerr/cnfgfile.go
pkg/unpackerr/handlers.go
pkg/unpackerr/lidarr.go
pkg/unpackerr/logs.go
pkg/unpackerr/radarr.go
pkg/unpackerr/readarr.go
pkg/unpackerr/sonarr.go
pkg/unpackerr/start.go
pkg/unpackerr/tray.go
pkg/unpackerr/whisparr.go

- Closes #415 
- Adds app uptime to queue log.

disconnect poll interval from delay timer

---

pkg/unpackerr/folder.go
pkg/unpackerr/logs.go

retry folders when delete delay beats retry delay

---

.github/workflows/release.yml
.golangci.yml
examples/unpackerr.conf.example
go.mod
pkg/unpackerr/apps.go
pkg/unpackerr/cnfgfile.go
pkg/unpackerr/folder.go
pkg/unpackerr/tray.go

folder clean up. 
also updates go version in build, and addresses some lint

clean up folders.go

---

pkg/unpackerr/cmdhook.go
pkg/unpackerr/cnfgfile.go
pkg/unpackerr/folder.go
pkg/unpackerr/handlers.go
pkg/unpackerr/lidarr.go
pkg/unpackerr/logs.go
pkg/unpackerr/radarr.go
pkg/unpackerr/readarr.go
pkg/unpackerr/sonarr.go
pkg/unpackerr/webserver.go
pkg/unpackerr/whisparr.go

- Consolidates the `validate` functions for each starr.
- Adds homedir expansion to all starr paths.
- Adds homedir expansion to folder paths and extract paths.
- Adds homedir expansion to command hook commands.
- Closes #453

Expand home dir everywhere

---

init/config/definitions.yml

doc update

---

.github/workflows/release.yml
Makefile
examples/docker-compose.yml
examples/unpackerr.conf.example

This will create and upload 3 Arch Linux zst package to GitHub when there's a new release.

create binary arch package for github release

---

Makefile
init/archlinux/PKGBUILD.template

Previous PR missed a few lines. Sign all the files!
Also fixing this:
```
:: Processing package changes...
...
warning: directory permissions differ on /etc/unpackerr/
filesystem: 755  package: 775
warning: directory permissions differ on /usr/share/doc/unpackerr/
filesystem: 755  package: 775
```

Sign all the TXZ and ZST files.

---

init/install.sh

update install.sh script

---

examples/docker-compose.yml
examples/unpackerr.conf.example
init/config/compose.go
init/config/definitions.yml
init/config/main.go

add overrides for examples and docker

---

pkg/unpackerr/apps.go
pkg/unpackerr/folder.go

set default for folder delete after to 10m

---

examples/docker-compose.yml
examples/unpackerr.conf.example
init/config/definitions.yml
pkg/unpackerr/apps.go
pkg/unpackerr/cnfgfile.go
pkg/unpackerr/folder.go
pkg/unpackerr/logs.go
pkg/unpackerr/start.go

Allows changing the log file mode.

---

pkg/unpackerr/handlers.go

add multi-file 7z support to starr apps
