examples/unpackerr.conf.example
Fixing the torrent protocol name in the example config file.
After spending quite some time debugging why it wasn't picking up the files to extract that small was the culprit, I had that file copy and pasted.
=> Fix torrent protocol name

examples/MANUAL.md, init/systemd/template.unit.service, pkg/unpackerr/folder.go, pkg/unpackerr/start.go, pkg/unpackerr/webhook.go, pkg/unpackerr/webhook_samples.go, scripts/after-install.sh
- Fixes some bugs encountered when trying to use the `folder` feature on Windows. Seems to work now!
- Adds an `unpackerr` user and group to linux packages. Adds `UMask` option too, defaulted to group writable.
- To use this on Linux, add your other apps to the `unpackerr` group.
- Add `Sonarr` user to `unpackerr` group like this: `usermod -G unpackerr sonarr`
- Adds code to provide sending fake Webhooks [for testing and development].
=> Fix bugs with windows+folders. Add unpackerr user/group and webhook test

pkg/unpackerr/logs.go, pkg/unpackerr/start.go
This contribution fixes the initialization and use of the internal Logger interface. Basically, it was being initialized out of order and passing in default values to `lumberjack` and the rest of the logging piece. whoops. This corrects that mistake so log rotation works as configured.
This also exposes any log-write errors to the console. They were being hidden previously. Also adds a link to discord.
=> Fix log rotation

README.md, examples/unpackerr.conf.example, pkg/unpackerr/apps.go, pkg/unpackerr/handlers.go, pkg/unpackerr/lidarr.go, pkg/unpackerr/radarr.go, pkg/unpackerr/readarr.go, pkg/unpackerr/sonarr.go, pkg/unpackerr/start.go
Closes #83 and closes #86.
Moves `delete_delay` from main app struct into each sub-app struct, so it can be configured independently. Also adds `delete_orig` so you can choose to delete original files upon successful extraction. I don't recommend set this value to true, but a NZB user requested it.
**Deprecates global `delete_after` and `timeout` variables.**
=> Add two new features involving file deletion.

README.md, examples/MANUAL.md, examples/unpackerr.conf.example, pkg/unpackerr/folder.go, pkg/unpackerr/lidarr.go, pkg/unpackerr/radarr.go, pkg/unpackerr/readarr.go, pkg/unpackerr/sonarr.go, pkg/unpackerr/webhook.go, pkg/unpackerr/webhook_samples.go, pkg/unpackerr/webhooks_templates.go, settings.sh
Closes #82 by adding support for sending Webhooks to discord directly. Also supports Slack natively. You can also pass in your own POST template and send Webhooks to anything you want.
=> Add discord and slack direct webhook support.

pkg/unpackerr/logs.go, pkg/unpackerr/logs_linux.go, pkg/unpackerr/logs_others.go, pkg/unpackerr/logs_windows.go, pkg/unpackerr/radarr.go, pkg/unpackerr/sonarr.go, settings.sh
This contribution fixes a crash/panic when Radarr or Sonarr are configured, but not properly responding. It also fixes a bug that prevented panic messages (stack traces) from being written to the log file.
=> Crash fix and Panic Logs fix

README.md, pkg/unpackerr/webhook.go, pkg/unpackerr/webhooks_templates.go
This contribution adds a built-in template for sending pushover webhook messages.
```
[[webhook]]
name    = "Pushover"
url     = "https://api.pushover.net/1/messages.json"
token   = "API_TOKEN"
channel = "USER_TOKEN"
```
=> Add pushover web hook template.

README.md
`$UN_{SON,RAD,READ,LID}ARR_0_DELETE_DELAY` is supposedly able to take `-1`, but that crashes the program and the value instead needs to be `-1s`.
=> Environment variable value specified in README.md doesn't crash the program

pkg/unpackerr/folder.go
Closes #215 by normalizing folder paths before watching them.
This change is available on docker @ `golift/unpackerr:unstable`
=> Normalize folder paths.

pkg/unpackerr/webhooks_templates.go
Closes #231 by fixing the Slack web hook template.
=> fix slack template error

pkg/unpackerr/folder.go
This fixes the bug provided in #248.
What happens: When the app starts it initializes an fsnotify structure, but if no folders are defined it does not use it. If this initialization fails, for any reason, the app now has an uninitialized data structure and later crashes when it tries to read it. The bug discovered shows a failure in this initialization due to `too many open files`. Never seen this, and this bug has never been brought up until now.
So, to fix it, I did two things.
1. We no longer initialize fsnotify if there are no folders defined. This will avoid the `too many open files` problem.
2. If the fsnotify initialization fails, we still create the data structure to avoid crashing the app.
=> fix crash when folder watcher fails

init/docker/Dockerfile
This avoids trying to figure out what's eating CPU in htop and related applications:
=> docker: set `unpackerr` as entrypoint

README.md, examples/MANUAL.md, go.mod, go.sum, main.go, pkg/ui/ui_darwin.go, pkg/ui/ui_other.go, pkg/ui/ui_windows.go, pkg/unpackerr/cnfgfile.go
- Removes the code for the Windows console window. Finishes #223
- Writes a config file in Docker if `/config` exists. Closes #259
=> Remove console-window code

.github/workflows/codetests.yml, pkg/unpackerr/folder.go
- Closes #320.
Removes the error (and web hook/command hook) for folders with no compressed files in them.
=> no error when folder has no compressed files

examples/unpackerr.conf.example
This addresses a small error in the documentation for `cmdhook`s.
=> Fix inaccurate cmdhook example instructions comment

.gitattributes, .gitignore, pkg/unpackerr/folder.go, pkg/unpackerr/logs.go
This will allow the `cmdhook`s and `webhook`s to trigger when there is nothing to extract.
Previously just a log message was output into the logs and then the item was removed from further processing.
This will allow users to react with `cmdhook`s and/or `webhook`s to an item being processed that has nothing to extract.
=> Adds the extractednothing ExtractStatus

pkg/unpackerr/lidarr.go, pkg/unpackerr/radarr.go, pkg/unpackerr/readarr.go, pkg/unpackerr/sonarr.go, pkg/unpackerr/whisparr.go
At some point we added an API Key length check and that began disallowing zero-length keys. The unraid template relies on zero-length keys and the app won't start by default. 
- Allows configurations with no API Key (zero length).
- Apps with zero length keys are ignored and skipped.
- Fixes #408.
=> Fixes a bug where no API Key prevents the app from starting

pkg/unpackerr/handlers.go
Hi there,
I was hit with an error today that stated:
```
handlers.go:197: Extraction Error: blabla.rar: os.MkdirAll: mkdir /home/transmission/Lidarr/lidarr/blabla.rar_unpackerred: permission denied
```
except that this showed with an `[INFO]` priority level, and so I missed it for a while before reading through again.
I took the liberty of making this simple change so that message (and one other I feel is an error rather than an "INFO") will be printed as such.
Thanks for taking this into consideration.
Regards
Mark
=> Replace some u.Printf calls with u.Errorf in handlers.go

examples/unpackerr.conf.example, pkg/unpackerr/logs.go
- Closes #434 
Turns out there's no need to add a message since a log file is always set on operating systems with a tray menu. While looking into it, I realized home folder (~) was not being taken into account when viewing the log file, so I fixed that. Also updated the comment in the example config file.
=> Fix log file path for viewing

pkg/unpackerr/cnfgfile.go, pkg/unpackerr/folder.go, pkg/unpackerr/start.go
- Closes #419 
- Closes #413 
- Closes #396
- Adds a minimum poll interval. If you wish to disable it while in docker, set the interval to "1ms"
- Ignores log files in the watch folder.
- Prints the config file age on startup.
=> ignore log file, add minimum poll interval, print config file age

go.mod, go.sum, pkg/unpackerr/start.go
This allows putting a tilde ~ in a `filepath:<path>` to expand it to a home folder.
=> allow homedir expansion with filepath: notation

pkg/unpackerr/history.go, pkg/unpackerr/start.go, pkg/unpackerr/tray.go, pkg/unpackerr/tray_other.go
=> Fix history bug

.github/workflows/release.yml, .gitignore, Makefile, examples/docker-compose.yml, examples/unpackerr.conf.example
This uses gpg to sign the FreeBSD and Arch Linux packages. The sig files are uploaded to GitHub releases.
=> Sign ZST and TXZ packages.

pkg/unpackerr/webhooks_templates.go
=> Remove expanding of URL previews

init/config/definitions.yml
https://github.com/Unpackerr/unpackerr/issues/484#issuecomment-2295402012
=> docs: add clarify delete_after needing to be greater than 0

.github/workflows/codetests.yml, .golangci.yml, examples/docker-compose.yml, examples/unpackerr.conf.example, main.go, pkg/ui/dlgs_other.go, pkg/unpackerr/apps.go, pkg/unpackerr/logs.go, pkg/unpackerr/start.go, pkg/unpackerr/tray.go, pkg/unpackerr/webhook.go, pkg/unpackerr/webserver.go
Updates golang ci linter to latest version and addresses all the lint problems it found.
Fixes a bug where I broke the freebsd and linux builds.
=> Update linter, fix some bugs
